// AUTO-GENERATED by scripts/build-git-history.mjs — DO NOT EDIT MANUALLY.
// Regenerate via `pnpm history:update`. The hidden /secret-import-history
// page joins this with client/src/data/importHistory.ts on the commit hash.

export interface GitCommit {
  hash: string;
  shortHash: string;
  date: string; // ISO 8601
  author: string;
  subject: string;
  files: string[];
}

export const gitHistoryGeneratedAt = "2026-06-24T09:38:35.497Z";

export const gitHistory: GitCommit[] = [
  {
    "hash": "47d8c37545f49e80863a970a17066f0efe02bee7",
    "shortHash": "47d8c37",
    "date": "2026-06-24T09:37:28+00:00",
    "author": "Claude",
    "subject": "feat(content): finance.skaile.de — /screen + /morning-note, Analyse-Caveat",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "dab52ff7f6f342ce8fa265dd4b2e5ef5d900258d",
    "shortHash": "dab52ff",
    "date": "2026-06-11T09:26:31+02:00",
    "author": "janstarcke",
    "subject": "feat(skills): Claude Fable 5 activation skill #108 (#46)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "adb4ce9ea3139b304041d59a7bf921602d476fe4",
    "shortHash": "adb4ce9",
    "date": "2026-06-11T09:23:17+02:00",
    "author": "janstarcke",
    "subject": "feat(skills): extend Higgsfield MCP #40 — 5 tools, web path, Soul detail (#45)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "cb14e6739155456ff01848a51b4e1ee31a5949a1",
    "shortHash": "cb14e67",
    "date": "2026-06-11T09:20:34+02:00",
    "author": "janstarcke",
    "subject": "feat(skills): grill-me skill #107 — structured pre-coding interview (#44)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "7b87f03b21f4e225ca49197d2bdfd0db154f69e7",
    "shortHash": "7b87f03",
    "date": "2026-06-11T09:13:49+02:00",
    "author": "janstarcke",
    "subject": "feat(skills): Graphify skill #106 — 70x token reduction via knowledge graph (#43)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "6b1f72acf88e75ee96bde0802e64f4bb8adb7b30",
    "shortHash": "6b1f72a",
    "date": "2026-06-11T07:03:23+02:00",
    "author": "janstarcke",
    "subject": "feat(content): Security-Guidance-Plugin (#105) + TL;DR-Item (#42)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "ac3ac2bf6cc37da6fa4eb48ef6400448872aacd1",
    "shortHash": "ac3ac2b",
    "date": "2026-06-10T21:32:35+02:00",
    "author": "janstarcke",
    "subject": "chore(history): retrofit catalog entry for c029521 (#103/#104 + EXTEND #20/#84) (#41)",
    "files": [
      "client/src/data/importHistory.ts"
    ]
  },
  {
    "hash": "782a797e2b5bc01f63057fe2a962ceedca0dd9f0",
    "shortHash": "782a797",
    "date": "2026-06-10T21:30:09+02:00",
    "author": "janstarcke",
    "subject": "feat(content): Obsidian Second Brain — EXTEND #20 (MCP-Weg, Query/Lint, Such-Falle) (#40)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "c029521ae5152e355cf4d868e045284599697ae9",
    "shortHash": "c029521",
    "date": "2026-06-04T09:56:05-07:00",
    "author": "janstarcke",
    "subject": "feat(content): Security-Checkliste + NotebookLM + 2 EXTENDS (#103, #104, #20, #84) (#38)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "3db7304ca6fd9a7f83d5e4f2f63c64ae92531701",
    "shortHash": "3db7304",
    "date": "2026-05-31T12:31:29-07:00",
    "author": "janstarcke",
    "subject": "feat(content): ultracode cost warning + CLAUDE.md schutz-block (EXTEND #102) (#36)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "688a524f63bd4e8c09acedf2ce1b14ece9caebe0",
    "shortHash": "688a524",
    "date": "2026-05-31T12:20:07-07:00",
    "author": "janstarcke",
    "subject": "feat(content): Dynamic Workflows — 1 new + 1 extend (#102) (#35)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "fb20f9f1ac5b4b155ddf8277f878e48014cb48f4",
    "shortHash": "fb20f9f",
    "date": "2026-05-31T12:14:10-07:00",
    "author": "janstarcke",
    "subject": "feat(content): Opus 4.8 setup-guide — 3 new + 1 extend (#99–#101) (#34)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "481111e6ba2fed8693210d4265dd0e2e16deb8e7",
    "shortHash": "481111e",
    "date": "2026-05-28T12:35:48-07:00",
    "author": "janstarcke",
    "subject": "feat(content): Karpathy-CLAUDE.md skill (#98) (#33)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "9576838657304f2a7e12fc68c8c929ddef5d9466",
    "shortHash": "9576838",
    "date": "2026-05-28T12:28:47-07:00",
    "author": "janstarcke",
    "subject": "feat(content): ECC Agent-Harness-Komplettpaket (#97) (#32)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "b819983f00ad852062020bd304a3b1c1bb2d52eb",
    "shortHash": "b819983",
    "date": "2026-05-26T01:44:12-07:00",
    "author": "janstarcke",
    "subject": "fix(content): #95 Sentry MCP — correct HTTP endpoint (#28)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "106e7c5d8c518ae226ac0798ddb4a25f1f270fe1",
    "shortHash": "106e7c5",
    "date": "2026-05-26T01:32:03-07:00",
    "author": "janstarcke",
    "subject": "feat(content): 3 Dev-MCPs (#94-#96) + EXTEND #33 Remotion (#27)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "5c4a275deaa3be36e6de034d1f080aeea36b14ae",
    "shortHash": "5c4a275",
    "date": "2026-05-25T18:42:07+02:00",
    "author": "Jan Starcke",
    "subject": "feat(content): #93 Hyperframes HTML→MP4 für Claude Code",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "061b20ecdcb226584f8cd8e084101356d5357706",
    "shortHash": "061b20e",
    "date": "2026-05-25T18:40:37+02:00",
    "author": "Jan Starcke",
    "subject": "feat(content): #92 NEW + #51/#72 EXTEND aus team/gary/gehirn (3 Quellen)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "f095856dcd36d907da5649f95e92f61cfbc8dcbc",
    "shortHash": "f095856",
    "date": "2026-05-25T18:34:31+02:00",
    "author": "Jan Starcke",
    "subject": "feat(content): claude.ai Projects 4-Folder-Foundation (#91)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "b32b1e3af5c5ed6796916e318877ecd3e18f6b5e",
    "shortHash": "b32b1e3",
    "date": "2026-05-25T17:47:32+02:00",
    "author": "Jan Starcke",
    "subject": "feat(content): Open Design — OSS-Alternative zu Claude Design (#90)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "b05869148ab8edb75292a172734c2b496cf0c5ff",
    "shortHash": "b058691",
    "date": "2026-05-25T16:48:19+02:00",
    "author": "Jan Starcke",
    "subject": "feat(content): Paperclip Multi-Agent-Orchestrator (#89)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "3b255c099c1156ee458d230f5ee3cbac9f86eb9e",
    "shortHash": "3b255c0",
    "date": "2026-05-18T16:46:22-07:00",
    "author": "janstarcke",
    "subject": "feat(history): pre-push auto-regenerate hook + catalog #84-#88 (#18)",
    "files": [
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "0bb508f9bf43cd8e3a5ecb4bd68f92adcef392c9",
    "shortHash": "0bb508f",
    "date": "2026-05-18T16:38:00-07:00",
    "author": "janstarcke",
    "subject": "chore(history): catalog #68-#83 + regenerate import history (#17)",
    "files": [
      "client/src/data/importHistory.ts"
    ]
  },
  {
    "hash": "c846731ea74f71fb2a97de9d56ee6a03d7e3871d",
    "shortHash": "c846731",
    "date": "2026-05-18T16:25:52-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): 5 neue Skills aus Ultimatives-Tutorial (#79-#83)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "074195a402f329745d2cdf91123a088248ac97fe",
    "shortHash": "074195a",
    "date": "2026-05-18T16:19:04-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): Deploy-Go-Live skill + Routines-Quota (#78, #31)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "d837d667de40e996f2bfb0e74735fbb2b9784f9b",
    "shortHash": "d837d66",
    "date": "2026-05-18T15:43:44-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): GitHub-Safety + lokale Modelle (#76, #77)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "96fa1303049c3fc44dc22ce6375bad80d74c1301",
    "shortHash": "96fa130",
    "date": "2026-05-18T15:39:01-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): MCP-Sammlung, CLI-Hack, CLAUDE.md-Interview (#73-#75, #33, #37)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "dc02c38d9771cc5709132edeb2b63ac3bbb66dfb",
    "shortHash": "dc02c38",
    "date": "2026-05-18T15:34:53-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): 3 plugin skills + 2 plugin refreshes (#70-#72, #38, #51)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "70eced41b313ff3ec2c0a97d5e50b3675332d33f",
    "shortHash": "70eced4",
    "date": "2026-05-16T06:38:20-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): Claude for Small Business + Mahn-Pipeline (#68, #69)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "b19e45fe5ed661aad774a6f401e2ed1e2536aac1",
    "shortHash": "b19e45f",
    "date": "2026-05-15T18:29:09+02:00",
    "author": "janstarcke",
    "subject": "fix(a11y): #29c final — all 5 main pages Lighthouse A11y 100/100 (#13)",
    "files": [
      "client/src/data/guide.ts",
      "client/src/data/importHistory.ts",
      "client/src/data/skills.ts"
    ]
  }
];
