// AUTO-GENERATED by scripts/build-git-history.mjs — DO NOT EDIT MANUALLY.
// Regenerate via `pnpm history:update`. The hidden /secret-import-history
// page joins this with client/src/data/importHistory.ts on the commit hash.

export interface GitCommit {
  hash: string;
  shortHash: string;
  date: string; // ISO 8601
  author: string;
  subject: string;
  files: string[];
}

export const gitHistoryGeneratedAt = "2026-05-13T15:33:50.703Z";

export const gitHistory: GitCommit[] = [
  {
    "hash": "6a7494d6c0e08c3b36684ad914e42d835dfc65aa",
    "shortHash": "6a7494d",
    "date": "2026-05-13T07:06:46-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): refine AI Finance Team skill (#47)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "a52d2b450164dcca93df6d0bc0a96fc64cd2d64f",
    "shortHash": "a52d2b4",
    "date": "2026-05-13T07:05:01-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): add Layered Analysis Prompt skill (#59)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "89393dad1d07b31c20fd9e5831679855ac58b926",
    "shortHash": "89393da",
    "date": "2026-05-13T05:29:54-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): add Personal Finance skills (#57, #58)",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "fa4908737cae3d65214903094327af5944623497",
    "shortHash": "fa49087",
    "date": "2026-05-13T05:15:20-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): Equity Research plugin + complete 10-agent list",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "2aac0f6609ca656e5fbba49054bce2bd06625650",
    "shortHash": "2aac0f6",
    "date": "2026-05-12T20:59:40-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): integrate Claude Managed Agents (CMA) intro",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "6b4d976029ff34327125cd4730dfd17494de4f62",
    "shortHash": "6b4d976",
    "date": "2026-05-12T20:44:02-07:00",
    "author": "Jan Starcke",
    "subject": "feat(content): Agent View — Background-Sessions parallel",
    "files": [
      "client/src/data/skills.ts"
    ]
  },
  {
    "hash": "bc470b2bcd51abd4a82c348cbec55d1691ba5ad5",
    "shortHash": "bc470b2",
    "date": "2026-05-12T19:54:31-07:00",
    "author": "Jan Starcke",
    "subject": "feat: initial release",
    "files": [
      "client/src/data/guide.ts",
      "client/src/data/skills.ts"
    ]
  }
];
